### ISSUE TITLE
Suggestion: Suppression des valeurs déjà tirées

### ISSUE THREAD

**Issue by vgrandidier** [paulintrognon/plouf-plouf#31]
Bonjour,
Je souhaite effectuer un tirage pour savoir qui va offrir un cadeau à qui pour une soirée.
J'utilise donc Plou-Plouf dans 2 fenêtres.
Il serait donc bien de pouvoir supprimer les valeurs déjà tirées avant de lancer un nouveau tirage.
Merci.

**Comment by paulintrognon** [comment]
Bonjour vgrandidier !

Merci pour cette suggestion. Je viens d'ajouter une nouvelle fonctionnalitée au site qui permet, après un tirage, de revenir en arrière pour pouvoir facilement ajouter / supprimer des valeurs.

Ça permet de faire à peu près ce que vous demandez !

Merci et cordialement
