### ISSUE TITLE
List importation

### ISSUE THREAD

**Issue by medline2c** [paulintrognon/plouf-plouf#36]
Lorsqu'il y a beaucoup de noms, on ne voit pas tout dans la page : possible de mettre dans une fenêtre qui s'agrandit ou au pire modifiable pour tout voir ?
Au delà, ce serait vraiment génial de pouvoir importer une liste avec un séparateur comme la virgule qui est simple à parser ?... ou sinon importer une liste depuis un fichier texte (avec tabulation, retour à la ligne ou virgule, point-virgule ... ce qui est le mieux à coder) ? J'ai eu 120 noms à ajouter à la main, un à un et j'ai fait une fausse manipulation, j'ai du tout refaire... pas super pratique du coup ?... est-ce possible ou trop compliqué ?
Félicitations sinon, c'est une super idée !

**Comment by paulintrognon** [comment]
Bonjour et merci pour votre commentaire !

**Pour l'import :**
Je peux en effet ajouter une fonctionnalité pour importer une liste. Je vais réfléchir à la manière la plus simple de procéder !

**Pour la modification**
Il est déjà possible de modifier une liste sans avoir à tout réécrire grâce au bouton "modifier". L'aviez vous vu ? Peut-être dois-je rendre cette fonctionnalité plus explicite.
![Capture d’écran de 2020-10-09 16-21-13](https://user-images.githubusercontent.com/1859396/95595046-07d31b80-0a4c-11eb-808e-acfd5cc893e5.png)

**Quand il y a beaucoup de noms**
Premièrement, êtes vous sur téléphone mobile ou sur ordinateur ?
Je veux être sûr de bien comprendre votre demande. Actuellement, quand il y a beaucoup de noms, je limite l'affichage des noms en hauteur, avec une barre de défilement à droite :
![Capture d’écran de 2020-10-09 16-21-13](https://user-images.githubusercontent.com/1859396/95594832-bcb90880-0a4b-11eb-95b6-921256b95888.png)

Vous suggérez que j'affiche tous les noms, c'est bien ça ?

Merci encore pour vos suggestions !

**Comment by medline2c** [comment]
Bonjour;

Merci pour votre réponse rapide ! je vais utiliser votre solution demain et
dimanche devant 200 personnes !... ;-)

Pour répondre à vos questions :

   - Pour import : je vous laisse voir côté code en effet. J'avais
   personnellement pensé à un copier/coller avec 1 joueur par ligne (on
   détecte ainsi le retour à la ligne)...
   - Pour le bouton Modifier : oui j'avais vu;... par contre, le bouton "+
   Nouveau" est dangereux... peut-être le renommer "Tout effacer" ... ? Je me
   suis fait avoir la première fois... (on pourrait croire : Ajouter un nom
   ...)
   - Quand Beaucoup de noms : je suis sur ORDINATEUR puisque j'affiche mon
   écran sur un vidéo projecteur en pleine image (la fenêtre du navigateur en
   PLEIN ECRAN F11) ...
   - L'idéal serait qu'il n'y ait pas d'ascenseur pour TOUT afficher :
   charge à faire un Zoom Moins pour afficher la page à 90% si tout ne rentre
   pas... ce qui simplifie le code (sinon il faudrait gérer la taille de la
   police ... bref)
   - Je suggère donc que TOUS les noms s'affichent, oui
   - Je réitère que, moyennant une case à cocher peut-être, ce serait top
   que le nom tiré au sort soit supprimé de la liste... et aussi, donner la
   possibilité de tirer N personnes en une seule fois... là vous passeriez
   loin devant les autres systèmes que j'ai vu qui le proposent  car vous avez
   l'avantage d'avoir le côté visuel qui est très intéressant !
   - Félicitations pour votre code !


Belle journée !

Christophe CARPENTIER
Port. 06 45 63 37 26



Le ven. 9 oct. 2020 à 16:26, Paulin Trognon <notifications@github.com> a
écrit :

**Comment by paulintrognon** [comment]
@medline2c je vous recommande de supprimer le numéro de téléphone de votre message précédent car le contenu de cette page est accessible publiquement. Cordialement
