### ISSUE TITLE
Analytics script raises a 502

### ISSUE THREAD

**Issue by sly7-7** [paulintrognon/plouf-plouf#45]
Hi, 

I was wondering if the data entered were in some way kept or sent to a server. It seems they aren't, even if there is an analytics script expected to be executed when the app starts.
Currently, loading this script raises 
![Capture d’écran 2020-12-23 à 09 21 21](https://user-images.githubusercontent.com/1826661/102975361-3c5d5c00-4500-11eb-879c-9f8909b40f42.png)

**Comment by paulintrognon** [comment]
Hi,

Plausible, the tool I self-host for analytics, was down (and has been for a long time). I restarted it and checked if it tracked users input, and in fact it does, by sending the result URL to plausible.

As I do not want users to be tracked, I removed Plausible Analytics entirely, so you can be sure that no data you entered are sent back to the server :slightly_smiling_face:

**Comment by sly7-7** [comment]
I think it's a great move, thank you :)
Very nice tool by the way !!
