### ISSUE TITLE
Toujours Lilian qui tombe !

### ISSUE THREAD

**Issue by Lilian6pack** [paulintrognon/plouf-plouf#51]
Pourquoi c'est toujours moi qui est tiré au sort

**Comment by paulintrognon** [comment]
Normalement le tirage au sort est toujours aléatoire ! Un tirage aléatoire ne veut pas forcément dire qu'à chaque fois quelqu'un de différent doit être tiré. Il peut arriver que la même personne soit tirée au sort plusieurs fois de suite. Voir cet article sur [le sophisme du joueur](https://dantotsupm.com/2020/01/07/biais-cognitifs-lerreur-du-parieur-ou-sophisme-du-joueur/) pour en savoir plus.

 Je pense simplement que vous n'avez pas eu de chance... :disappointed: N'hésitez pas si vous avez d'autres questions !
